apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-rest-api
  template:
    metadata:
      labels:
        app: go-rest-api
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: go-rest-api
        image: hariregistry007.azurecr.io/go-rest-api:v1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-rest-api
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: go-rest-api